# 3.	Conceptos básicos: variables, tipos de datos y sus operaciones

## Mostrar información por pantalla

Lo primero que hacemos cuando empezamos a aprender un nuevo lenguaje de programación es llamar a la instrucción que nos muestre un mensaje por pantalla. En este caso mostraremos el mensaje "Hola mundo".

Para ello podemos ver que se utiliza la función ```print(<mensaje>)``` escribiendo dentro de los parentesis el mensaje concreto entre comillas simples.

In [1]:
print('Hola Mundo')

Hola Mundo

Si queremos mostrar varios mensajes por pantalla, únicamente tenemos que escribir varias instrucciones.

In [23]:
print('Hola Mundo 1')
print('Hola Mundo 2')

Hola Mundo 1
Hola Mundo 2

Sin embargo, vemos que al ejecutar print() añade al mensaje un salto de línea, el cual hace que el segundo mensaje aparezca en una linea nueva. Esto lo podemos evitar añadiendo un nuevo parámetro a ```print(<mensaje>, end='')```

In [42]:
print('Hola Mundo 1 ', end='')
print('Hola Mundo 2')

Hola Mundo 1 Hola Mundo 2

## Las variables

De forma muy simple podemos considerar una variable como un espacio de memoria que almacena información, dicho espacio en memoria va a tener dos atributos principalmente:

1. Un nombre único que nos permita acceder a la información de forma inequívoca. Se le llamará identificador (o nombre) de la variable.

2. La información almacenada en memoria. La información que asignamos a una variable puede ser de diveros tipos, como por ejemplo cadenas, números, letras, etc.

La forma de definir una variable con un nombre único y asignarle un valor se hace de la siguiente forma:

```<nombreVariable> = <valor de la variable>```

Por ejemplo, en la siguiente línea de código definiremos la variabla ```x``` con el valor ```5```.

```x = 5```

A continuación veremos tres tipos de variables básicas en Python: números, booleanos y cadenas. En el siguiente código se ve como inicializamos una variable de cada uno de los tipos.

In [36]:
numero = 5
booleano = True
cadena = 'Esto es una cadena'

#podemos utilizar la función type(<nombreVariable>) para mostrar el tipo
print(type(numero))   #int que corresponde a un entero
print(type(booleano)) #bool que corresponde a booleano
print(type(cadena))   #str que corresponde a cadena

print('Se puede cambiar el tipo durante la ejecución.')

<class 'int'>
<class 'bool'>
<class 'str'>
Se puede cambiar el tipo durante la ejecución.

### Numeros

Ya sabemos que los números pueden corresponder a diferentes tipos; como por ejemplo enteros y reales.

#### Enteros

No importa lo grandes que sean los enteros, siempre los gestionaremos de la misma forma.

In [38]:
x = 1
print(x)
print(type(x))

1
<class 'int'>

In [40]:
x = 432523452345
print(x)
print(type(x))

432523452345
<class 'int'>

##### Operaciones aritméticas

In [51]:
n1 = 10
n2 = 15

#suma
print('La suma de n1 y n2')
print(n1 + n2)
print(type(n1 + n2))

#multiplicación
print('')
print('La multiplicación de n1 y n2')
print(n1 * n2)
print(type(n1*n2))

#resta
print('')
print('La resta de n1 y n2')
print(n1 - n2)
print(type(n1 - n2))

#división con decimales
print('')
print('La división de n1 y n2')
print(n1 / n2)
print(type(n1 / n2)) #se puede ver que el tipo es float, que lo veremos más adelante

#división entera
print('')
print('La división ENTERA de n1 y n2')
res1 = n1//n2
print(res1)
print(type(res1))

#modulo
print('')
print('Módulo division n1 % n2:', n1 % n2)
print('Módulo division 3 % 2:', 3 % 2)

#exponencial
print('')
print('El resultado de a elevado a b')
a = 5
b = 3
print(a ** b)

#obtener valor absoluto
print('')
print('El valor absoluto de -5')
print(abs(-5))

La suma de n1 y n2
25
<class 'int'>

La multiplicación de n1 y n2
150
<class 'int'>

La resta de n1 y n2
-5
<class 'int'>

La división de n1 y n2
0.6666666666666666
<class 'float'>

La división ENTERA de n1 y n2
0
<class 'int'>

Módulo division n1 % n2: 10
Módulo division 3 % 2: 1

El resultado de a elevado a b
125

El valor absoluto de -5
5

#### Reales

Al igual que los enteros, no importa su longitud, se gestionarán todos de la misma forma. **Cuidado, tienes que utilizara el punto para separar la parte entera de la decimal**.

In [8]:
temperatura = 21.5
print(temperatura)
print(type(temperatura))

21.5
<class 'float'>

##### Operaciones aritméticas

In [53]:
print(2.3 + 1.5) #suma
print(1.5 / 2.3) #división con decimales
print(1.5 * 2.3) #multiplicación
print(2.3 - 1.5) #resta
print(1.5 - 2.3) #resta

i = 3 * 0.1 #multiplicación (cuidado con el sesgo)
print(i)

#aunque el resultado pueda ser un entero, se almacena como real
print(type(2.0 * 2))
print(type(2.5 * 2))

3.8
0.6521739130434783
3.4499999999999997
0.7999999999999998
-0.7999999999999998
0.30000000000000004
<class 'float'>
<class 'float'>

#### Operaciones generales con números

Extisten una serie de funciones que se pueden utilizar tanto con enteros como reales independientemente del tipo.

In [10]:
#Obtener el máximo de una serie de valores. Función max(n1, n2, n3, ...)
n1 = 2
n2 = 3
n3 = 0
print(max(n1,n2,n3))

3

In [11]:
#Obtener el minimo de una serie de valores. Función min(n1, n2, n3, ...)
n1 = 2
n2 = 3
n3 = 0
print(min(n1,n2,n3))

0

In [55]:
#Obtener la suma de una serie de valores. Función sum()
a= (1,2,3,4,5,6) #tipo de dato que no hemos visto (se llama tupla)
print(sum(a))

21

### Booleanos

Las variables booleanas únicamente pueden ser del tipo *True* o *False*. El equivalente de int y float en los booleanos es bool.

In [13]:
all_ok = True
print(all_ok)

all_ok = False
print(all_ok)

print(type(all_ok))

True
False
<class 'bool'>

Se puede traducir el valor booleano a entero:

In [57]:
print(int(True))
print(int(False))

print(bool(1))
print(bool(0))

1
0
True
False

##### Operadores lógicos
Cuando trabajamos con variables booleanos podemos utilizar los operadores lógicos AND, OR y NOT que corresponden con las operaciones lógicas de AND, OR y NOT.

**Tabla de AND**

|       | True  | False |
|-------|-------|-------|
| True  | True  | False |
| False | False | False |

In [61]:
print(True and True)
print(True and False)
print(False and True)
print(False and False)

True
False
False
False
False


**Tabla de OR**

|       | True  | False |
|-------|-------|-------|
| True  | True  | True |
| False | True  | False |

In [16]:
print(True or True)
print(True or False)
print(False or True)
print(False or False)

True
True
True
False

**Tabla de NOT**

|       | NOT  |
|-------|-------|
| True  | False  |
| False | True  |

In [17]:
print(not True)
print(not False)

False
True

##### Operadores Relacionales

Los operadores relacionales son aquellos que devuelven un valor booleano a partir de comparaciones de expresiones numéricas o cadenas.

| Simbolo | Descripcion       | Ejemplo |
|---------|-------------------|---------|
| ==      | Igual que         | 2 == 3  |
| !=      | Diferente a       | 2 != 3  |
| <       | Menor que         | 2 < 3   |
| <=      | Menor o igual que | 2 <= 3  |
| >       | Mayor que         | 2 > 3   |
| >=      | Mayor o igual que | 2 >= 3  |

In [18]:
print(2==3)
print(2!=3)
print(2<3)
print(2<=3)
print(2>3)
print(2>=3)

False
True
True
True
False
False

### Cadenas

La definición de las cadenas en Python se realiza a través de las comillas simples (') o de comillas dobles ("), pero no mezclándolas. Por convención siempre se suelen utilizar las simples, excepto cuando dentro de la cadena haya que incluir una comilla doble.

**Nota**: utilizaremos la función ```type(<nombreVariable)``` para ver el tipo de información que almacena. En los siguientes casos muestra 'str' lo cual es una abreviatura de string (traducido a castellano como cadena).

#### Operaciones con Cadenas

A continuación veremos un conjunto de operaciones que vamos a poder realizar con variables de tipo cadena.

##### Concatenación
Podemos concatenar dos variables de la siguiente forma:

In [19]:
string_1 = 'Good'
string_2 = " day"
string_3 = string_1 + string_2
print(string_3)

Good day

In [62]:
#otro ejemplo lo podemos ver dentro de la función print.
print('Hello ' + 'World')

Hello World

Un escenario concreto de concatenación es cuando queremos concatenar una variable que almacena un número con una cadena. Veremos que da error:

In [69]:
msg = 'El numero: ' + 21
print(msg)

TypeError: can only concatenate str (not "int") to str

Para evitar dicho error deberemos cambiar el tipo de dato numérico a cadena. Para eso utilizamos la función ```str(<número>)```.

In [ ]:
msg = 'El numero:' + str(21)
print(msg)

Una forma interesante de concatenar también valores es con la siguiente estrategia.

In [70]:
entero1 = 31
cadena1 = 'Carlos'
print(f'{cadena1} dice que tiene {entero1} anios')

print('f es para concatenar')

Carlos dice que tiene 31 anios
f es para concatenar

##### Tamaño
Para ver el tamaño de una cadena se utiliza la función len(). Cuidado porque también cuenta espacios.

In [ ]:
print(len(string_3))

##### Acceder a una letra por posición.
Se puede acceder a una posición de la cadea untilizando la sintaxis ```<nombreVariable>[<posicion>]```. Por ejemplo, si queremos acceder a la posición cuatro de ```my_string``` lo haremos de la siguiente forma.

In [71]:
#Acceder a una posición. Se puede acceder a una letra concreta dentro de la cadena.
my_string = 'Hello World'
print(my_string[4])

o

##### Substring.
No solo podemos acceder a una posición concreta de la cadena, también podemos obtener una subcadena dando la posición inicial y la final. Para ello utilizarmos la sintaxis ```<nombreVariable>[<inicio>:<final>]```. A continuación se verán unos ejemplos.

In [73]:
#Substrings. También se puede recortar la cadena utilizando la posición de inicio y la posición final.
my_string = 'Hello World'
print(my_string[4])   # caracter en la posición 4
print(my_string[1:5]) # substring desde la posición 1 a la 5
print(my_string[:5])  # substring desde el principio hasta la posición 5
print(my_string[2:])  # substring desde la posición 2 hasta el final

#cuidado porque esto no modifica el valor de la variable
print(my_string)

#si deseamos modificarla podemos hacerlo con la asignación
my_string = my_string[2:5]
print(my_string)

o
ello
Hello
llo World
Hello World
llo

##### Trocear.

También se podrá trocear una cadena utilizando una cadena concreta. Para ello utilizarmos la función ```split``` con la siguiente sintaxis:

```<nombreVariable>.split(<caracterSeparacion>)```

 **Nota**: El resultado de dicho "troceamiento" dará como resultado una lista de cadenas. Una lista es otro tipo de dato que todavía no se ha explicado y que se hará más adelante.

Un ejemplo donde el trocear una cadena puede ser de utilidad es cuando queremos separar las palabras que componen dicha cadena. Para ello podemos trocearla utilizando el espacio (' ').

In [ ]:
texto = 'The Good, The Bad, and the Ugly'
print(texto.split(' '))

También puede ser útil cuando queremos separar frases, para ello podemos utilizar el punto.

In [80]:
texto = 'Frase 1. Frase 2. Frase 3.'
print(texto.split('.'))

['Frase 1', ' Frase 2', ' Frase 3', '']

##### Contabilizar apariciones
Se puede contabilizar las apariciones de un caracter utilizando la función ```count()``` con la sintaxis:

```<nombreVariable>.count(<cadenaContabilizar>)```

In [ ]:
my_string = 'Contador de numero de despacios'
print(my_string.count(' '))

También podríamos contabilizar el número de apariciones de una secuencia de caracters.

In [ ]:
my_string = 'Contador de numero de apariciones de "de"'
print(my_string.count('de'))

##### Busqueda de subcadenas.
Para la busqueda de subcadenas se utiliza la función ```find()``` con la sintaxis:

```<nombreVariable>.find(<cadenaBusqueda>)```

Esta función devolverá la posición en la que comienza la subcadena. En caso de que no exista devolverá -1.

In [ ]:
#Encontrar substring
cadena = 'Mi nombre es Carlos Sáenz'
print(cadena.find('Carlos')) #devuelve posición en la que empieza el substring y -1 si no aparece

##### Comparar cacenas.
Se pueden comparar cadenas mediante el simbolo "=="

In [ ]:
#Comparar strings
print('James' == 'James')
print('James' == 'John')
print('James' != 'John')
print('James' == 'james')
print("James" == 'James') #OJO, es True

##### Otras operaciones de utilidad

In [ ]:
#Otras operaciones muy útiles son las siguientes
some_string = 'Hello World'

#comprobar si comienza por ...
print("some_string.startswith('H')", some_string.startswith('H'))
print("some_string.startswith('h')", some_string.startswith('h'))

#comprobar si termina por ...
print("some_string.endswith('d')", some_string.endswith('d'))

#comprobar todas las palabras comienzan por mayúscula y si el resto de letras son minúscula
print('some_string.istitle()', some_string.istitle())

#comprobar si son mayúsculas, minúsculas
print('some_string.isupper()', some_string.isupper())
print('some_string.islower()', some_string.islower())

#comprobar si todos los caracteres son letras
print('some_string.isalpha()', some_string.isalpha())
print('')

#también podemos realizar conversiones
print('Conversiones')
print('some_string.upper()', some_string.upper()) #mayúsculas todo
print('some_string.lower()', some_string.lower()) #minúsculas todo
print('some_string.title()', some_string.title()) #cada palabra comienza en mayúscula y el resto son minúsculas
print('some_string.swapcase()', some_string.swapcase()) #intercambiar mayúsculas por minúsculas y viceversa
print('String leading, trailing spaces', " xyz ".strip()) #eliminar espacios al principio y final

## Recoger información por parte del usuario

La siguiente instrucción solicita al usuario el nombre de usuario y lo almacena en la variable *nombre_usuario*; posteriormente lo muestra por consola.

In [81]:
nombre_usuario = input('Nombre usuario: ')
print(nombre_usuario)

andrei

**OJO** porque todos los valores que introduzca el usuario se tomarán como una cadena.

In [88]:
numero = input('Introduce un número: ')
type(numero)

str

Si queremos tratarlo como un número debemos convertirlo con las funciones int() para enteros, float() para reales, boolean() para valores booleanos.

In [ ]:
numero = input('Introduce un número entero: ')
numero = int(numero)
type(numero)
print(numero)

In [ ]:
numero = input('Introduce un número decimal: ')
numero = float(numero)
type(numero)
print(numero)